/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blackJack.h"

bool_t
xdr_Card (XDR *xdrs, Card *objp)
{
	register int32_t *buf;

	if (!xdr_string (xdrs, &objp->face, ~0))
		return FALSE;
	if (!xdr_u_short (xdrs, &objp->point))
		return FALSE;
	return TRUE;
}

bool_t
xdr_Player (XDR *xdrs, Player *objp)
{
	register int32_t *buf;

	if (!xdr_u_short (xdrs, &objp->id))
		return FALSE;
	if (!xdr_array (xdrs, (char **)&objp->cards.cards_val, (u_int *) &objp->cards.cards_len, ~0,
		sizeof (Card), (xdrproc_t) xdr_Card))
		return FALSE;
	return TRUE;
}

bool_t
xdr_GameStatus (XDR *xdrs, GameStatus *objp)
{
	register int32_t *buf;

	if (!xdr_Player (xdrs, &objp->player))
		return FALSE;
	if (!xdr_Player (xdrs, &objp->dealer))
		return FALSE;
	if (!xdr_u_short (xdrs, &objp->currentPointsOfPlayer))
		return FALSE;
	if (!xdr_u_short (xdrs, &objp->currentPointsOfDealer))
		return FALSE;
	if (!xdr_string (xdrs, &objp->msg, ~0))
		return FALSE;
	return TRUE;
}

bool_t
xdr_HitRequest (XDR *xdrs, HitRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->gameStatus, sizeof (GameStatus), (xdrproc_t) xdr_GameStatus))
		return FALSE;
	if (!xdr_u_short (xdrs, &objp->id))
		return FALSE;
	return TRUE;
}

bool_t
xdr_GameResult (XDR *xdrs, GameResult *objp)
{
	register int32_t *buf;

	if (!xdr_u_short (xdrs, &objp->finalPointsOfPlayer))
		return FALSE;
	if (!xdr_u_short (xdrs, &objp->finalPointsOfDealer))
		return FALSE;
	if (!xdr_string (xdrs, &objp->result, ~0))
		return FALSE;
	return TRUE;
}
